apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  spec:
    containers:
    - name:aa
      image:aaa
      env:
      - name:
        value:
      - name:
        value: